### ISSUE TITLE
Job manifests should be validated and universal

### ISSUE THREAD

**Issue by LookACastle** [TheRacetrack/racetrack#231]
Job manifests are currently not validated properly, leading to both potential messes in the future, and some current minor annoyances with racetrack. Their rules are also not universal for all job types (for example, python has special rules, as does golang, de facto limiting job type development).

For example, if someone produces a job type for a language where they'd like some customization of some sort, they have to either homebrew a solution outside of the [spec](https://github.com/TheRacetrack/racetrack/blob/b2ff0e29994e907f121ee00de8d287783dbed8d0/docs/manifest-schema.md) (For example, see [the Hugo jobtypes manifests](https://github.com/TheRacetrack/plugin-hugo-job-type/blob/0e97b2d3d09ca4c1fc5723d3d59431fa194e0472/sample/job.yaml) which has `wrapper_properties`), or they have to touch the main racetrack repository like we've done for `go` with the `golang` key, and `python` with the `python` key.

You can also have "wrong" manifests that follow our current schema. For example, if you make a job manifest with `name: no`, you get an error that the repository name must be lowercase. If you know YAML, you know that `no` becomes `False`, but it's not intuitive, and better validation would allow a better error message to occur, "`name` is of type boolean, it must be of type string" or similar. 

---

I propose that we make the spec universal, such that there's no more special job type keys, `lang` better reflect that job types don't have to be languages, and add a universal `jobtype-specific` key or similar, which is a YAML list that holds whatever the job type developer wants it to hold. `jobtype-specific` will be the replacement for fields like `python` and `golang`

I further propose that we introduce 2 steps of validation, one for the universal YAML, and one for the job type specific list. Racetrack core can validate everything outside of the jobtype specific key, and the job type developer should make sure their own specific fields are validated. 

The validation could be done using some schema tool like [Yamale](https://github.com/23andMe/Yamale), though I personally have no strong opinion on exactly how we do it, as long as it gets done.

**Comment by JosefAssadERST** [comment]
Seeing how it's me that bullied @LookACastle into posting this, here's how I interpret the proposal in a mockup:

# Python example

```yaml
---
# CURRENT
name: meow
owner_email: meow@example.com
lang: python3:latest
git:
  remote: https://example.com/yeehaw
  branch: master
 python:
  requirements_path: 'supersmart/requirements.txt'
  entrypoint_path: 'job_entrypoint.py'
```

```yaml
---
# PROPOSED
name: meow  # validated by RT core
owner_email: meow@example.com  # validated by RT core
jobtype: python3:latest  # validated by RT core
git:  # validated by RT core
  remote: https://example.com/yeehaw  # validated by RT core
  branch: master  # validated by RT core
 jobtype_extra:  # validated by RT core
  requirements_path: 'supersmart/requirements.txt'   # validated by jobtype plugin
  entrypoint_path: 'job_entrypoint.py'   # validated by jobtype plugin
```

# Golang example

```yaml
 ---
# CURRENT
name: meow
owner_email: meow@example.com
lang: golang:latest
git:
  remote: https://example.com/yeehaw
  branch: master
golang:
  gomod: 'go.mod'
```

```yaml
 ---
# PROPOSED
name: meow  # validated by RT core
owner_email: meow@example.com  # validated by RT core
jobtype: golang:latest  # validated by RT core
git:  # validated by RT core
  remote: https://example.com/yeehaw  # validated by RT core
  branch: master  # validated by RT core
jobtype_extra:  # validated by RT core
  gomod: 'go.mod'   # validated by jobtype plugin
 ```
