### ISSUE TITLE
Keep original manifest Yaml

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#262]
A job manifest displayed on dashboard can be different from the Yaml file deployed by a user.
This is weird. 
It happens so, because YAML string is parsed to pydantic `Manifest` Python object, which may apply some defaults, for instance it adds `image_type: str = 'docker'` field. This ends up in a final manifest being different from an actual manifest that has been deployed.
It should display the original one, especially now that we allow to edit them and want to keep them in sync with the version in git.
Also, defaults can change over time and we should keep record of a original YAML file.

## Example
Original file:
```yaml
name: adder
owner_email: sample@example.com
jobtype: python3:latest
version: 0.0.2

git:
  remote: https://github.com/theracetrack/racetrack
  directory: sample/python-class

jobtype_extra:
  requirements_path: 'requirements.txt'
  entrypoint_path: 'adder.py'
  entrypoint_class: 'AdderModel'
```

Manifest in the Lifecycle's database:
```yaml
git:
  directory: sample/python-class
  remote: https://github.com/theracetrack/racetrack
image_type: docker
jobtype: python3:latest
jobtype_extra:
  entrypoint_class: AdderModel
  entrypoint_path: adder.py
  requirements_path: requirements.txt
name: adder
owner_email: sample@example.com
replicas: 1
version: 0.0.2
```

Notice additional `image_type` and `replicas` fields.
